### ISSUE TITLE
cannot import graphcompass

### ISSUE THREAD

**Issue by spatts14** [theislab/graphcompass#69]
Hi,

I've tried to use an old environiment I had set up fro graphcompass that previously worked. However, I was getting an error about numpy/numba. I deleted the environment and made a new one an installed only graphcompass and ipykernel using pip install. Can you please advise? 

When I try to import graphcompass and Im getting this error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[3], line 7
      4 import warnings
      5 warnings.filterwarnings("ignore")
----> 7 import graphcompass as gc
      8 from graphcompass import pl
      9 from graphcompass import tl

File [~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/__init__.py:2](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/__init__.py:2)
      1 """Graph-COMPASS."""
----> 2 from graphcompass import pl
      3 from graphcompass import tl
      4 from graphcompass import datasets

File [~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/pl/__init__.py:2](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/pl/__init__.py:2)
      1 """The plotting module."""
----> 2 from . import _distance as distance
      3 from . import _WLkernel as wlkernel
      4 from . import _filtration_curves as filtration_curves

File [~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/pl/_distance.py:14](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/miniforge3/envs/graphcompass/lib/python3.11/site-packages/graphcompass/pl/_distance.py:14)
     11 from matplotlib.figure import Figure
     13 from tqdm import tqdm
---> 14 from graphcompass.tl._distance import compare_groups
...
      8 if use_dask_expr is False:
----> 9     raise NotImplementedError("The legacy implementation is no longer supported")
     11 return True

NotImplementedError: The legacy implementation is no longer supported
```

Here are all the packages
```
graphcompass) sarapatti@Saras-MacBook-Pro-3 IMC_pipeline % pip list
Package                  Version
------------------------ -----------
aiobotocore              2.5.4
aiohappyeyeballs         2.6.1
aiohttp                  3.11.14
aioitertools             0.12.0
aiosignal                1.3.2
anndata                  0.11.3
appnope                  0.1.4
array_api_compat         1.11.2
asciitree                0.3.3
asttokens                3.0.0
attrs                    25.3.0
botocore                 1.31.17
certifi                  2025.1.31
charset-normalizer       3.4.1
click                    8.1.8
cloudpickle              3.1.1
colorcet                 3.1.0
comm                     0.2.2
contourpy                1.3.1
cycler                   0.12.1
Cython                   3.0.12
dask                     2025.3.0
dask-image               2024.5.3
datashader               0.17.0
debugpy                  1.8.13
decorator                5.2.1
Deprecated               1.2.18
distributed              2025.3.0
docrep                   0.3.2
exceptiongroup           1.2.2
executing                2.1.0
fasteners                0.19
fonttools                4.56.0
frozenlist               1.5.0
fsspec                   2023.6.0
geopandas                1.0.1
graphcompass             0.2.5
h5py                     3.13.0
idna                     3.10
igraph                   0.11.8
imageio                  2.37.0
importlib_metadata       8.6.1
inflect                  7.5.0
ipykernel                6.29.5
ipython                  9.0.2
ipython_pygments_lexers  1.1.1
jedi                     0.19.2
Jinja2                   3.1.6
jmespath                 1.0.1
joblib                   1.4.2
jupyter_client           8.6.3
jupyter_core             5.7.2
kiwisolver               1.4.8
lazy_loader              0.4
legacy-api-wrap          1.4.1
leidenalg                0.10.2
llvmlite                 0.44.0
locket                   1.0.0
markdown-it-py           3.0.0
MarkupSafe               3.0.2
matplotlib               3.10.1
matplotlib-inline        0.1.7
matplotlib-scalebar      0.9.0
mdurl                    0.1.2
more-itertools           10.6.0
msgpack                  1.1.0
multidict                6.2.0
multipledispatch         1.0.0
multiscale_spatial_image 1.0.1
natsort                  8.4.0
nest_asyncio             1.6.0
NetLSD                   1.0.2
networkx                 3.4.2
numba                    0.61.0
numcodecs                0.15.1
numpy                    2.1.3
ome-zarr                 0.10.3
omnipath                 1.0.9
packaging                24.2
pandas                   2.2.3
param                    2.2.0
parso                    0.8.4
partd                    1.4.2
patsy                    1.0.1
pexpect                  4.9.0
pickleshare              0.7.5
pillow                   11.1.0
PIMS                     0.7
pip                      25.0.1
platformdirs             4.3.7
pooch                    1.8.2
POT                      0.9.5
prompt_toolkit           3.0.50
propcache                0.3.0
psutil                   7.0.0
ptyprocess               0.7.0
pure_eval                0.2.3
pyarrow                  19.0.1
pyct                     0.5.0
Pygments                 2.19.1
pynndescent              0.5.13
pyogrio                  0.10.0
pyparsing                3.2.3
pyproj                   3.7.1
python-dateutil          2.9.0.post0
pytz                     2025.2
PyWavelets               1.8.0
PyYAML                   6.0.2
pyzmq                    26.3.0
requests                 2.32.3
rich                     13.9.4
s3fs                     2023.6.0
scanpy                   1.11.0
scikit-image             0.20.0
scikit-learn             1.5.2
scipy                    1.15.2
seaborn                  0.13.2
session-info2            0.1.2
setuptools               75.8.2
shapely                  2.0.7
six                      1.17.0
slicerator               1.1.0
sortedcontainers         2.4.0
spatial_image            1.1.0
spatialdata              0.2.5.post0
squidpy                  1.6.2
stack_data               0.6.3
statannot                0.2.3
statsmodels              0.14.4
tblib                    3.0.0
texttable                1.7.0
threadpoolctl            3.6.0
tifffile                 2025.3.13
toolz                    1.0.0
tornado                  6.4.2
tqdm                     4.67.1
traitlets                5.14.3
typeguard                4.4.2
typing_extensions        4.12.2
tzdata                   2025.2
umap-learn               0.5.7
urllib3                  1.26.20
validators               0.34.0
wcwidth                  0.2.13
wheel                    0.45.1
wrapt                    1.17.2
xarray                   2024.7.0
xarray-dataclasses       1.9.1
xarray-datatree          0.0.15
xarray-schema            0.0.3
xarray-spatial           0.4.0
yarl                     1.18.3
zarr                     2.18.4
zict                     3.0.0
zipp                     3.21.0
```

**Comment by mayarali** [comment]
Hi @spatts14, thanks for raising the issue. Can you please try to downgrade `numpy` to a version <2.0. This should solve the numpy/numba issue.

**Comment by spatts14** [comment]
Thanks for getting back to me! Apologies on the slow response on my part. 

I downgrade to 1.26.4 however I am still getting this issue

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[2], line 8
      5 warnings.filterwarnings("ignore")
      7 import scanpy as sc
----> 8 import graphcompass as gc
      9 import pandas as pd
     10 import numpy as np

File [~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/__init__.py:2](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/__init__.py:2)
      1 """Graph-COMPASS."""
----> 2 from graphcompass import pl
      3 from graphcompass import tl
      4 from graphcompass import datasets

File [~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/pl/__init__.py:2](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/pl/__init__.py:2)
      1 """The plotting module."""
----> 2 from . import _distance as distance
      3 from . import _WLkernel as wlkernel
      4 from . import _filtration_curves as filtration_curves

File [~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/pl/_distance.py:14](https://file+.vscode-resource.vscode-cdn.net/Users/sarapatti/Desktop/PhD_projects/Llyod_lab/IMC_pipeline/SP_IMC/scripts/GraphCompass/~/Desktop/PhD_projects/_Other/git_packages/graphcompass/src/graphcompass/pl/_distance.py:14)
     11 from matplotlib.figure import Figure
     13 from tqdm import tqdm
---> 14 from graphcompass.tl._distance import compare_groups
...
      8 if use_dask_expr is False:
----> 9     raise NotImplementedError("The legacy implementation is no longer supported")
     11 return True

NotImplementedError: The legacy implementation is no longer supported
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?75668dc2-7ae3-4fdc-b616-ba2fc16b2ffd) or open in a [text editor](command:workbench.action.openLargeOutput?75668dc2-7ae3-4fdc-b616-ba2fc16b2ffd). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```

Here is an updated list of packages installed

```
# Name                    Version                   Build  Channel
aiobotocore               2.5.4                    pypi_0    pypi
aiohappyeyeballs          2.6.1                    pypi_0    pypi
aiohttp                   3.11.14                  pypi_0    pypi
aioitertools              0.12.0                   pypi_0    pypi
aiosignal                 1.3.2                    pypi_0    pypi
anndata                   0.11.3                   pypi_0    pypi
appnope                   0.1.4              pyhd8ed1ab_1    conda-forge
array-api-compat          1.11.2                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
attrs                     25.3.0                   pypi_0    pypi
botocore                  1.31.17                  pypi_0    pypi
bzip2                     1.0.8                hfdf4475_7    conda-forge
ca-certificates           2025.1.31            h8857fd0_0    conda-forge
certifi                   2025.1.31                pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
click                     8.1.8                    pypi_0    pypi
cloudpickle               3.1.1                    pypi_0    pypi
colorcet                  3.1.0                    pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.3.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.12                   pypi_0    pypi
dask                      2025.3.0                 pypi_0    pypi
dask-image                2024.5.3                 pypi_0    pypi
datashader                0.17.0                   pypi_0    pypi
debugpy                   1.8.13          py311hc356e98_0    conda-forge
decorator                 5.2.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.18                   pypi_0    pypi
distributed               2025.3.0                 pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_1    conda-forge
executing                 2.1.0              pyhd8ed1ab_1    conda-forge
fasteners                 0.19                     pypi_0    pypi
fonttools                 4.56.0                   pypi_0    pypi
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
geopandas                 1.0.1                    pypi_0    pypi
graphcompass              0.2.5                    pypi_0    pypi
h5py                      3.13.0                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
igraph                    0.11.8                   pypi_0    pypi
imageio                   2.37.0                   pypi_0    pypi
importlib-metadata        8.6.1              pyha770c72_0    conda-forge
inflect                   7.5.0                    pypi_0    pypi
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   9.0.2              pyhfb0248b_0    conda-forge
ipython_pygments_lexers   1.1.1              pyhd8ed1ab_0    conda-forge
jedi                      0.19.2             pyhd8ed1ab_1    conda-forge
jinja2                    3.1.6                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jupyter_client            8.6.3              pyhd8ed1ab_1    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
kiwisolver                1.4.8                    pypi_0    pypi
krb5                      1.21.3               h37d8d59_0    conda-forge
lazy-loader               0.4                      pypi_0    pypi
legacy-api-wrap           1.4.1                    pypi_0    pypi
leidenalg                 0.10.2                   pypi_0    pypi
libcxx                    20.1.1               hf95d169_0    conda-forge
libedit                   3.1.20250104    pl5321ha958ccf_0    conda-forge
libexpat                  2.6.4                h240833e_0    conda-forge
libffi                    3.4.6                h281671d_0    conda-forge
liblzma                   5.6.4                hd471939_0    conda-forge
libsodium                 1.0.20               hfdf4475_0    conda-forge
libsqlite                 3.49.1               hdb6dae5_2    conda-forge
libzlib                   1.3.1                hd23fc13_2    conda-forge
llvmlite                  0.44.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.10.1                   pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
matplotlib-scalebar       0.9.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
more-itertools            10.6.0                   pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.2.0                    pypi_0    pypi
multipledispatch          1.0.0                    pypi_0    pypi
multiscale-spatial-image  1.0.1                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.5                  h0622a9a_3    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_1    conda-forge
netlsd                    1.0.2                    pypi_0    pypi
networkx                  3.4.2                    pypi_0    pypi
numba                     0.61.0                   pypi_0    pypi
numcodecs                 0.15.1                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
ome-zarr                  0.10.3                   pypi_0    pypi
omnipath                  1.0.9                    pypi_0    pypi
openssl                   3.4.1                hc426f3f_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pandas                    2.2.3                    pypi_0    pypi
param                     2.2.0                    pypi_0    pypi
parso                     0.8.4              pyhd8ed1ab_1    conda-forge
partd                     1.4.2                    pypi_0    pypi
patsy                     1.0.1                    pypi_0    pypi
pexpect                   4.9.0              pyhd8ed1ab_1    conda-forge
pickleshare               0.7.5           pyhd8ed1ab_1004    conda-forge
pillow                    11.1.0                   pypi_0    pypi
pims                      0.7                      pypi_0    pypi
pip                       25.0.1             pyh8b19718_0    conda-forge
platformdirs              4.3.7              pyh29332c3_0    conda-forge
pooch                     1.8.2                    pypi_0    pypi
pot                       0.9.5                    pypi_0    pypi
prompt-toolkit            3.0.50             pyha770c72_0    conda-forge
propcache                 0.3.0                    pypi_0    pypi
psutil                    7.0.0           py311h4d7f069_0    conda-forge
ptyprocess                0.7.0              pyhd8ed1ab_1    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_1    conda-forge
pyarrow                   19.0.1                   pypi_0    pypi
pyct                      0.5.0                    pypi_0    pypi
pygments                  2.19.1             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.13                   pypi_0    pypi
pyogrio                   0.10.0                   pypi_0    pypi
pyparsing                 3.2.3                    pypi_0    pypi
pyproj                    3.7.1                    pypi_0    pypi
python                    3.11.11         h9ccd52b_2_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-igraph             0.11.8                   pypi_0    pypi
python_abi                3.11                    5_cp311    conda-forge
pytz                      2025.2                   pypi_0    pypi
pywavelets                1.8.0                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.3.0          py311hb21797c_0    conda-forge
readline                  8.2                  h7cca4af_2    conda-forge
requests                  2.32.3                   pypi_0    pypi
rich                      13.9.4                   pypi_0    pypi
s3fs                      2023.6.0                 pypi_0    pypi
scanpy                    1.11.0                   pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.15.2                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
session-info2             0.1.2                    pypi_0    pypi
setuptools                75.8.2             pyhff2d567_0    conda-forge
shapely                   2.0.7                    pypi_0    pypi
six                       1.17.0             pyhd8ed1ab_0    conda-forge
slicerator                1.1.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
spatial-image             1.1.0                    pypi_0    pypi
spatialdata               0.2.5.post0              pypi_0    pypi
squidpy                   1.6.2                    pypi_0    pypi
stack_data                0.6.3              pyhd8ed1ab_1    conda-forge
statannot                 0.2.3                    pypi_0    pypi
statsmodels               0.14.4                   pypi_0    pypi
tblib                     3.0.0                    pypi_0    pypi
texttable                 1.7.0                    pypi_0    pypi
threadpoolctl             3.6.0                    pypi_0    pypi
tifffile                  2025.3.13                pypi_0    pypi
tk                        8.6.13               h1abcd95_1    conda-forge
toolz                     1.0.0                    pypi_0    pypi
tornado                   6.4.2           py311h4d7f069_0    conda-forge
tqdm                      4.67.1                   pypi_0    pypi
traitlets                 5.14.3             pyhd8ed1ab_1    conda-forge
typeguard                 4.4.2                    pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2025.2                   pypi_0    pypi
umap-learn                0.5.7                    pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
validators                0.34.0                   pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
wrapt                     1.17.2                   pypi_0    pypi
wwl                       0.1.2                    pypi_0    pypi
xarray                    2024.7.0                 pypi_0    pypi
xarray-dataclasses        1.9.1                    pypi_0    pypi
xarray-datatree           0.0.15                   pypi_0    pypi
xarray-schema             0.0.3                    pypi_0    pypi
xarray-spatial            0.4.0                    pypi_0    pypi
yarl                      1.18.3                   pypi_0    pypi
zarr                      2.18.4                   pypi_0    pypi
zeromq                    4.3.5                h7130eaa_7    conda-forge
zict                      3.0.0                    pypi_0    pypi
zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
```

**Comment by KSimi7** [comment]
Hi!

Thank you for creating this package. I got the same error when I tried to import graphcompass after installing it. I downgraded numpy to 2.0.0 but still had the legacy issue. I tried downgrading further but could not successfully build wheels for lower versions of numpy.

**Comment by KSimi7** [comment]
Hi!! 

I tried a couple of things but I am facing the same issue. I tried downgrading the environment to python=3.10 which was mentioned in another issue. I also tried installing graphcompass version 0.2.0 but I am still getting the same legacy error when trying to import graphcompass.

![Image](https://github.com/user-attachments/assets/2a8a3f21-a71d-409d-9f6c-85ce47402986)

**Comment by KSimi7** [comment]
Hi again! 

Sorry for commenting multiple times. I found the error source is from spatial-data incompatibility to latest version of dask which I found on this thread :
https://github.com/scverse/spatialdata/issues/835

Downgrading dask to the version specified in the above thread and downgrading numpy to 1.26 worked!

**Comment by spatts14** [comment]
Thanks so much @KSimi7! Worked for me too.
